# Generated by Django 3.0.8 on 2020-07-19 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FAQ',
            new_name='FAQQuestions',
        ),
    ]
