# Generated by Django 3.0.8 on 2020-07-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0002_auto_20200719_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqquestions',
            name='Answer',
            field=models.TextField(max_length=4000),
        ),
    ]
