# Generated by Django 3.0.8 on 2020-07-24 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0003_auto_20200719_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faqquestions',
            old_name='Category',
            new_name='CategoryID',
        ),
    ]
