# Generated by Django 3.0.8 on 2020-07-24 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0004_auto_20200724_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faqquestions',
            old_name='CategoryID',
            new_name='Category',
        ),
    ]
