# Generated by Django 3.0.8 on 2020-08-10 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Orders', '0006_remove_orders_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SessionID', models.CharField(max_length=50)),
                ('Image', models.ImageField(default='default.png', upload_to='images/')),
                ('Date', models.DateField(auto_now_add=True)),
                ('OrderNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.Orders')),
            ],
        ),
    ]
