# Generated by Django 3.0.8 on 2020-08-10 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ImageUpload', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='Image',
            new_name='ImageName',
        ),
    ]
