# Generated by Django 3.1.1 on 2020-09-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageUpload', '0002_auto_20200810_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='ImageName',
            field=models.ImageField(default='default.png', upload_to='images/%Y/%m/%d'),
        ),
    ]
