# Generated by Django 3.1.1 on 2020-09-26 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0023_auto_20200925_2149'),
        ('ImageUpload', '0003_auto_20200915_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='Order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Orders.orders'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='ImageName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='OrderNo',
            field=models.IntegerField(),
        ),
    ]
