# Generated by Django 3.1.1 on 2020-09-26 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ImageUpload', '0004_auto_20200926_0816'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
