# Generated by Django 3.1.1 on 2020-11-23 16:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Collections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collections',
            name='Date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collections',
            name='Name',
            field=models.CharField(default='Image', max_length=200),
        ),
    ]
