# Generated by Django 3.1.1 on 2020-11-24 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Collections', '0002_auto_20201123_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(default='Image', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='collections',
            name='Category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Collections.collectioncategory'),
            preserve_default=False,
        ),
    ]
