# Generated by Django 3.1.1 on 2020-11-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderNo', models.IntegerField()),
                ('SessionID', models.CharField(max_length=50)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Time', models.TimeField(auto_now_add=True)),
                ('Email', models.CharField(max_length=3)),
            ],
        ),
    ]
