# Generated by Django 3.1.1 on 2020-11-18 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MailList', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailinglist',
            name='OrderNo',
        ),
    ]
