# Generated by Django 3.1.1 on 2020-11-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MailList', '0003_auto_20201118_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglist',
            name='Active',
            field=models.BooleanField(default=True),
        ),
    ]
