# Generated by Django 3.1.1 on 2020-11-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MailList', '0004_mailinglist_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglist',
            name='Active',
            field=models.BooleanField(default=False),
        ),
    ]
