# Generated by Django 3.1.1 on 2020-11-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MailList', '0005_auto_20201118_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglist',
            name='Token',
            field=models.CharField(default=87797, max_length=400),
            preserve_default=False,
        ),
    ]
