# Generated by Django 3.1.1 on 2020-11-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MailList', '0006_mailinglist_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglist',
            name='SessionID',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mailinglist',
            name='Token',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
