# Generated by Django 3.1.1 on 2020-11-20 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MailList', '0007_auto_20201120_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailinglist',
            old_name='Date',
            new_name='dtm',
        ),
        migrations.RenameField(
            model_name='mailinglist',
            old_name='Time',
            new_name='tme',
        ),
    ]
