# Generated by Django 3.1.1 on 2020-11-20 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MailList', '0008_auto_20201120_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailinglist',
            old_name='dtm',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='mailinglist',
            old_name='tme',
            new_name='Time',
        ),
    ]
