# Generated by Django 3.1.1 on 2020-11-21 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MailList', '0009_auto_20201120_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('Time', models.TimeField(auto_now_add=True)),
                ('Newsletter', models.CharField(max_length=400)),
                ('Subject', models.CharField(max_length=400)),
                ('MailingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MailingList', to='MailList.mailinglist')),
            ],
        ),
    ]
