# Generated by Django 3.1.1 on 2020-11-22 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MailList', '0010_distribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestMailingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SessionID', models.CharField(max_length=50, null=True)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Time', models.TimeField(auto_now_add=True)),
                ('Email', models.CharField(max_length=400)),
                ('Active', models.BooleanField(default=False)),
                ('Token', models.CharField(max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('Time', models.TimeField(auto_now_add=True)),
                ('Newsletter', models.CharField(max_length=400)),
                ('Subject', models.CharField(max_length=400)),
                ('MailingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MailingList', to='MailList.testmailinglist')),
            ],
        ),
    ]
