# Generated by Django 3.1.1 on 2020-12-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MailList', '0011_testdistribution_testmailinglist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglist',
            name='SessionID',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='testmailinglist',
            name='SessionID',
            field=models.CharField(max_length=50),
        ),
    ]
