# Generated by Django 3.0.8 on 2020-07-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SizesAndPrices', '0002_auto_20200715_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizesandstock',
            name='Stock',
            field=models.IntegerField(),
        ),
    ]
