# Generated by Django 3.1.1 on 2020-12-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SizesAndPrices', '0003_auto_20200715_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizesandstock',
            name='Stock',
            field=models.IntegerField(default=0),
        ),
    ]
