# Generated by Django 3.1.1 on 2020-10-11 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingLocations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LocationCodes', models.CharField(max_length=50)),
                ('Price', models.IntegerField()),
                ('Addtional', models.IntegerField()),
                ('Status', models.CharField(default='Not Active', max_length=50)),
                ('ShippingLocations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Shipping.shippinglocations')),
            ],
        ),
    ]
