# Generated by Django 3.1.1 on 2020-10-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='Addtional',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='Status',
        ),
        migrations.AddField(
            model_name='shippinglocations',
            name='Addtional',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='shippinglocations',
            name='Price',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='shippinglocations',
            name='Status',
            field=models.CharField(default='Not Active', max_length=50),
        ),
    ]
