# Generated by Django 3.1.1 on 2020-12-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipping', '0002_auto_20201011_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippinglocations',
            name='Addtional',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shippinglocations',
            name='Price',
            field=models.IntegerField(default=0),
        ),
    ]
