# Generated by Django 3.0.8 on 2020-08-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_orders_imagepath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='ImageName',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='ImagePath',
        ),
        migrations.AddField(
            model_name='orders',
            name='Image',
            field=models.ImageField(default='default.png', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='deliverydetails',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
