# Generated by Django 3.0.8 on 2020-08-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_auto_20200807_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Image',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
    ]
