# Generated by Django 3.0.8 on 2020-08-10 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0005_auto_20200810_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='Image',
        ),
    ]
