# Generated by Django 3.0.8 on 2020-08-10 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0006_remove_orders_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordernumber',
            name='SessionID',
        ),
    ]
