# Generated by Django 3.1.1 on 2020-09-08 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0007_remove_ordernumber_sessionid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='ImageEdge',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='ImageStyle',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='OrderData',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='OrderEffect',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='OrderMaterial',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='OrderProof',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='OrderType',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='Qty',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='Size',
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Size', models.CharField(max_length=20)),
                ('ImageEdge', models.CharField(max_length=50)),
                ('ImageStyle', models.CharField(max_length=50)),
                ('Price', models.CharField(max_length=50)),
                ('Qty', models.IntegerField()),
                ('OrderData', models.CharField(max_length=2000)),
                ('OrderProof', models.CharField(max_length=100)),
                ('OrderType', models.CharField(max_length=100)),
                ('OrderMaterial', models.CharField(max_length=100)),
                ('OrderEffect', models.CharField(max_length=100)),
                ('OrderNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.orders')),
            ],
        ),
    ]
