# Generated by Django 3.1.1 on 2020-09-21 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0008_auto_20200908_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='ImageStyle',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='OrderData',
        ),
    ]
