# Generated by Django 3.1.1 on 2020-09-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0010_auto_20200922_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='AlternateDelivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='PaymentType',
            field=models.CharField(default='Direct bank Transfer', max_length=50),
        ),
    ]
