# Generated by Django 3.1.1 on 2020-09-24 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0011_auto_20200924_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverydetails',
            old_name='Area',
            new_name='delArea',
        ),
        migrations.RenameField(
            model_name='deliverydetails',
            old_name='Date',
            new_name='delDate',
        ),
        migrations.RenameField(
            model_name='deliverydetails',
            old_name='FirstName',
            new_name='delFirstName',
        ),
        migrations.RenameField(
            model_name='deliverydetails',
            old_name='House',
            new_name='delHouse',
        ),
        migrations.RenameField(
            model_name='deliverydetails',
            old_name='LastName',
            new_name='delLastName',
        ),
        migrations.RenameField(
            model_name='deliverydetails',
            old_name='PostCode',
            new_name='delPostCode',
        ),
        migrations.RenameField(
            model_name='deliverydetails',
            old_name='SessionID',
            new_name='delSessionID',
        ),
        migrations.RenameField(
            model_name='deliverydetails',
            old_name='Street',
            new_name='delStreet',
        ),
        migrations.RenameField(
            model_name='deliverydetails',
            old_name='Telephone',
            new_name='delTelephone',
        ),
        migrations.RenameField(
            model_name='deliverydetails',
            old_name='Town',
            new_name='delTown',
        ),
    ]
