# Generated by Django 3.1.1 on 2020-09-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0015_auto_20200924_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetails',
            name='PaymentType',
        ),
        migrations.AlterField(
            model_name='deliverydetails',
            name='OrderNo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='OrderNo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='OrderNo',
            field=models.IntegerField(),
        ),
    ]
