# Generated by Django 3.1.1 on 2020-09-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0016_auto_20200924_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Discount',
            field=models.FloatField(default=0),
        ),
    ]
