# Generated by Django 3.1.1 on 2020-09-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0017_auto_20200925_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Discount',
            field=models.FloatField(null=True),
        ),
    ]
