# Generated by Django 3.1.1 on 2020-09-25 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0018_auto_20200925_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverydetails',
            name='Order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.orders'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitems',
            name='Order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.orders'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='Order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.orders'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='Discount',
            field=models.FloatField(),
        ),
    ]
