# Generated by Django 3.1.1 on 2020-09-25 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0019_auto_20200925_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverydetails',
            name='Order',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='Order',
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='Order',
        ),
        migrations.AlterField(
            model_name='deliverydetails',
            name='OrderNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.orders'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='OrderNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.orders'),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='OrderNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.orders'),
        ),
    ]
