# Generated by Django 3.1.1 on 2020-09-25 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0021_auto_20200925_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ('OrderNo',)},
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='Order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Orders.orders'),
        ),
    ]
