# Generated by Django 3.1.1 on 2020-09-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0022_auto_20200925_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='Qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
