# Generated by Django 3.1.1 on 2020-09-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0024_auto_20200926_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='Proof',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='Proof',
            field=models.BooleanField(default=False),
        ),
    ]
