# Generated by Django 3.1.1 on 2020-09-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0025_auto_20200926_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='Image',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
