# Generated by Django 3.1.1 on 2020-10-11 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0026_orderitems_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shipping',
        ),
    ]
