# Generated by Django 3.1.1 on 2020-11-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0027_delete_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='AlternateDelivery',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Discount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='OrderStatus',
            field=models.CharField(max_length=200),
        ),
    ]
