# Generated by Django 3.1.1 on 2020-11-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0028_auto_20201112_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='Collection',
            field=models.BooleanField(default=False),
        ),
    ]
